import { PrismaClient } from "@prisma/client";
import { hashSync } from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  console.log("Criando dados iniciais...");

  // Operadores
  const admin = await prisma.operador.upsert({
    where: { id: 1 },
    update: { perfil: "ADMIN", pin: hashSync("2262", 10) },
    create: { nome: "Admin", pin: hashSync("2262", 10), perfil: "ADMIN" },
  });

  const operador2 = await prisma.operador.upsert({
    where: { id: 2 },
    update: { perfil: "OPERADOR", pin: hashSync("1234", 10) },
    create: { nome: "Maria", pin: hashSync("1234", 10), perfil: "OPERADOR" },
  });

  console.log(`Operadores: ${admin.nome} (PIN: 2262), ${operador2.nome} (PIN: 1234)`);

  // Limpa em ordem para respeitar FK constraints
  await prisma.movimentacaoEstoque.deleteMany({});
  await prisma.itemVenda.deleteMany({});
  await prisma.venda.deleteMany({});
  await prisma.pedidoDelivery.deleteMany({});
  await prisma.produto.deleteMany({});
  await prisma.categoria.deleteMany({});

  // Categorias
  const [cafe, acai, almoco, fit, lanches, salgados, tortasSalgadas, saladas, sopas, doces, guloseimas, bebidas, embalagens] = await Promise.all([
    prisma.categoria.create({ data: { nome: "Café", ordem: 1 } }),
    prisma.categoria.create({ data: { nome: "Açaí", ordem: 2 } }),
    prisma.categoria.create({ data: { nome: "Almoço", ordem: 3 } }),
    prisma.categoria.create({ data: { nome: "Fit", ordem: 4 } }),
    prisma.categoria.create({ data: { nome: "Lanches", ordem: 5 } }),
    prisma.categoria.create({ data: { nome: "Salgados", ordem: 6 } }),
    prisma.categoria.create({ data: { nome: "Tortas e Quiches", ordem: 7 } }),
    prisma.categoria.create({ data: { nome: "Saladas", ordem: 8 } }),
    prisma.categoria.create({ data: { nome: "Sopas", ordem: 9 } }),
    prisma.categoria.create({ data: { nome: "Doces e Sobremesas", ordem: 10 } }),
    prisma.categoria.create({ data: { nome: "Chocolates e Guloseimas", ordem: 11 } }),
    prisma.categoria.create({ data: { nome: "Bebidas", ordem: 12 } }),
    prisma.categoria.create({ data: { nome: "Embalagens", ordem: 13 } }),
  ]);

  console.log("Categorias criadas!");

  // ─── CAFÉ ───────────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Café Espresso", preco: 8.0, categoriaId: cafe.id },
      { nome: "Café Espresso Curto", preco: 7.0, categoriaId: cafe.id },
      { nome: "Café com Leite", preco: 8.0, categoriaId: cafe.id },
      { nome: "Café com Leite Baixo Açúcar", preco: 9.0, categoriaId: cafe.id },
      { nome: "Café Carioca", preco: 8.0, categoriaId: cafe.id },
      { nome: "Café Cappuccino", preco: 9.0, categoriaId: cafe.id },
      { nome: "Café Cappuccino com Chocolate", preco: 11.0, categoriaId: cafe.id },
      { nome: "Café Cappuccino Especial", preco: 11.0, categoriaId: cafe.id },
      { nome: "Café Cappuccino c/ Nutella", preco: 12.0, categoriaId: cafe.id },
      { nome: "Cappuccino Gelado Caramelo Salgado", preco: 12.0, categoriaId: cafe.id },
      { nome: "Cappuccino Gelado Zero", preco: 12.0, categoriaId: cafe.id },
      { nome: "Café Mocha", preco: 9.0, categoriaId: cafe.id },
      { nome: "Chocolate de Máquina", preco: 9.0, categoriaId: cafe.id },
      { nome: "Chá Camomila, Mel e Baunilha", preco: 8.0, categoriaId: cafe.id },
      { nome: "Chá Earl Grey - Bergamota", preco: 8.0, categoriaId: cafe.id },
      { nome: "Chá English Breakfast Preto", preco: 8.0, categoriaId: cafe.id },
      { nome: "Chá Gaseificado Camomila com Maracujá Devi", preco: 9.0, categoriaId: cafe.id },
      { nome: "Chá Gaseificado Verde com Pêssego Devi", preco: 9.0, categoriaId: cafe.id },
      { nome: "Chá Gelado", preco: 10.0, categoriaId: cafe.id },
      { nome: "Chá Lady Grey - Preto, Laranja e Limão", preco: 8.0, categoriaId: cafe.id },
      { nome: "Chá Limão com Gengibre, Laranja e Maçã", preco: 8.0, categoriaId: cafe.id },
      { nome: "Chá Twinings Frutos Silvestres", preco: 8.0, categoriaId: cafe.id },
      { nome: "Bebida Láctea Nescau", preco: 6.0, categoriaId: cafe.id },
      { nome: "Bebida Láctea Nesquik", preco: 6.5, categoriaId: cafe.id },
      { nome: "Bebida Láctea Toddynho", preco: 6.0, categoriaId: cafe.id },
      { nome: "Batida de Whey de Fruta", preco: 14.0, categoriaId: cafe.id },
      { nome: "Copo de Leite Puro", preco: 5.0, categoriaId: cafe.id },
    ],
  });

  // ─── AÇAÍ ───────────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Açaí - Pote 250 ml", preco: 14.0, categoriaId: acai.id },
      { nome: "Açaí - Pote 500 ml c/ 01 Opção Inclusa", preco: 22.0, categoriaId: acai.id },
      { nome: "Açaí em Copo com Complementos", preco: 24.0, categoriaId: acai.id },
      { nome: "Açaí - Suco de Polpa sem Fruta 500 ml", preco: 14.0, categoriaId: acai.id },
      { nome: "Complemento - Bananas", preco: 4.0, categoriaId: acai.id },
      { nome: "Complemento - Granola", preco: 3.0, categoriaId: acai.id },
      { nome: "Complemento - Leite Condensado", preco: 3.0, categoriaId: acai.id },
      { nome: "Complemento - Leite Ninho", preco: 3.0, categoriaId: acai.id },
      { nome: "Complemento - Morangos", preco: 4.0, categoriaId: acai.id },
      { nome: "Complemento - Nutella", preco: 7.0, categoriaId: acai.id },
    ],
  });

  // ─── ALMOÇO ─────────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Almoço - 1/2 Baby Beef à Parmegiana", preco: 37.0, categoriaId: almoco.id },
      { nome: "Almoço - Baby Beef à Parmegiana", preco: 47.5, categoriaId: almoco.id },
      { nome: "Almoço - Berinjela Parmegiana, Arroz e Saladinha", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Filé de Frango - Creme Milho", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Filé Frango ao Molho Catupiry e Arroz", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Filé Frango Grelhado, Arroz e Creme de Milho", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Filé Grelhado, Arroz com Espinafre", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Filé Grelhado, Arroz, Feijão e Mini Salada", preco: 30.0, categoriaId: almoco.id },
      { nome: "Almoço - Fraldinha, Arroz, Feijão, Salada ou Purê", preco: 48.0, categoriaId: almoco.id },
      { nome: "Almoço - Fricassê de Frango", preco: 32.0, categoriaId: almoco.id },
      { nome: "Almoço - Lasanha à Bolonhesa", preco: 31.0, categoriaId: almoco.id },
      { nome: "Almoço - Maminha, Arroz, Feijão, Salada ou Purê", preco: 48.0, categoriaId: almoco.id },
      { nome: "Almoço - Nhoque Recheado c/ Molho Branco", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Panqueca de Carne c/ Molho Verm. e Arroz", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Panqueca de Palmito", preco: 38.0, categoriaId: almoco.id },
      { nome: "Almoço - Panqueca de Frango c/ Molho Verm. e Arroz", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Panqueca Integral de Ricota c/ Espinafre e Arroz", preco: 36.0, categoriaId: almoco.id },
      { nome: "Almoço - Parmegiana de Frango c/ Arroz", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Raviollone Verde Recheado Mussarela, Molho Branco", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Risoto de Alho Porô c/ Limão", preco: 42.0, categoriaId: almoco.id },
      { nome: "Almoço - Risoto de Camarão", preco: 52.0, categoriaId: almoco.id },
      { nome: "Almoço - Risoto Funghi", preco: 42.0, categoriaId: almoco.id },
      { nome: "Almoço - Rodeli c/ Salada", preco: 29.5, categoriaId: almoco.id },
      { nome: "Almoço - Strogonoff de Carne c/ Arroz e Batata Palha", preco: 42.0, categoriaId: almoco.id },
      { nome: "Almoço - Strogonoff de Frango, Arroz e Batata Palha", preco: 35.0, categoriaId: almoco.id },
      { nome: "Almoço - Yakissoba Carne", preco: 37.0, categoriaId: almoco.id },
      { nome: "Almoço - Yakissoba Frango", preco: 32.0, categoriaId: almoco.id },
      { nome: "Almoço - Linguiça, Arroz, Feijão e Purê de Batata", preco: 30.0, categoriaId: almoco.id },
      { nome: "Conchiglione Quatro Queijos", preco: 32.0, categoriaId: almoco.id },
      { nome: "Escalope de Filé Mignon Acebolado, Arroz e Panachê Legumes", preco: 48.0, categoriaId: almoco.id },
      { nome: "Escalope de Filé Mignon ao Molho Madeira, Arroz e Panachê Legumes", preco: 48.0, categoriaId: almoco.id },
      { nome: "Escondidinho de Batata Doce e Frango", preco: 31.5, categoriaId: almoco.id },
      { nome: "Fricassê de Frango c/ Arroz e Batata Palha", preco: 32.0, categoriaId: almoco.id },
      { nome: "Lasanha 4 Queijos", preco: 32.0, categoriaId: almoco.id },
      { nome: "Nhoque", preco: 28.0, categoriaId: almoco.id },
      { nome: "Picadinho de Carne c/ Arroz e Feijão", preco: 42.0, categoriaId: almoco.id },
      { nome: "Raviolone Verde", preco: 35.0, categoriaId: almoco.id },
      { nome: "Rondelli de Espinafre c/ Mussarela", preco: 30.0, categoriaId: almoco.id },
      { nome: "Rondelli de Presunto e Queijo", preco: 30.0, categoriaId: almoco.id },
      { nome: "Strogonoff de Carne c/ Arroz e Batata Palha", preco: 42.0, categoriaId: almoco.id },
      { nome: "Strogonoff de Frango c/ Arroz e Batata Palha", preco: 35.0, categoriaId: almoco.id },
      { nome: "Mix p/ Risoto de Alho Porô c/ Limão", preco: 22.0, categoriaId: almoco.id },
      { nome: "Mix p/ Risoto de Camarão", preco: 33.0, categoriaId: almoco.id },
      { nome: "Mix p/ Risoto Funghi", preco: 22.0, categoriaId: almoco.id },
      { nome: "Arroz Arbóreo", preco: 11.0, categoriaId: almoco.id },
      { nome: "Arroz Branco Cozido", preco: 6.2, categoriaId: almoco.id },
      { nome: "Arroz Integral", preco: 6.6, categoriaId: almoco.id },
      { nome: "Feijão Carioca Cozido", preco: 7.4, categoriaId: almoco.id },
      { nome: "Creme de Milho", preco: 10.9, categoriaId: almoco.id },
      { nome: "Cuzcuz", preco: 12.5, categoriaId: almoco.id },
      { nome: "Legumes Panachê", preco: 9.8, categoriaId: almoco.id },
      { nome: "Molho Branco", preco: 7.6, categoriaId: almoco.id },
      { nome: "Molho de Tomate c/ Manjericão", preco: 7.8, categoriaId: almoco.id },
    ],
  });

  // ─── FIT ────────────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "FIT 1 - Croquete c/ Purê Bat. Doce e Arroz Integral c/ Mix Quinoa", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 2 - Lagarto c/ Purê de Mandioquinha e Arroz Integral", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 3 - Patinho c/ Legumes, Creme de Milho e Arroz Integral", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 4 - Feijoada Light c/ Arroz Integral e Couve Manteiga", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 5 - Frango c/ Barbecue, Creme de Espinafre e Arroz Sete Grãos", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 6 - Filé Frango c/ Creme Milho, Arroz Integral com Salsa", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 7 - Strogonoff de Frango, Arroz Integral, Cenoura e Brócolis", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 8 - Frango Desfiado com Cream Cheese e Batata Doce", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 9 - Lombo Suíno c/ Arroz Biro-biro", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 10 - Panqueca Integral de Carne ao Molho Sugo", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 11 - Panqueca Integral de Espinafre c/ Frango", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 12 - Escondidinho de Batata Doce c/ Frango", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 13 - Macarrão Integral ao Molho Bolonhesa", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 14 - Macarrão Integral ao Molho Branco Light c/ Brócolis", preco: 31.5, categoriaId: fit.id },
      { nome: "FIT 15 - Escondidinho de Mandioquinha c/ Carne Frita", preco: 36.0, categoriaId: fit.id },
      { nome: "FIT 16 - Strogonoff Filé Mignon, Arroz Integral e Couve Manteiga", preco: 36.0, categoriaId: fit.id },
      { nome: "FIT 17 - Strogonoff Palmito, Arroz Integral c/ Couve", preco: 36.0, categoriaId: fit.id },
      { nome: "FIT 18 - Panqueca Integral de 4 Queijos", preco: 36.0, categoriaId: fit.id },
      { nome: "FIT 19 - Baião de Dois Light", preco: 36.0, categoriaId: fit.id },
      { nome: "FIT 20 - Filet Tilápia ao Molho de Tomate e Arroz Integral c/ Lentilha", preco: 36.0, categoriaId: fit.id },
      { nome: "FIT 21 - Maminha Assada ao Molho Roti c/ Arroz Integral à Grega", preco: 36.0, categoriaId: fit.id },
      { nome: "FIT 22 - Fricassê de Frango c/ Vegetais", preco: 32.5, categoriaId: fit.id },
      { nome: "FIT 23 - Lasanha de Berinjela ao Molho Bolonhesa", preco: 34.0, categoriaId: fit.id },
      { nome: "FIT 24 - Escondidinho Abóbora com Carne - Low Carb", preco: 34.5, categoriaId: fit.id },
      { nome: "FIT 25 - Quinoa à Grega c/ Maminha Assada ao Molho Roti", preco: 36.0, categoriaId: fit.id },
    ],
  });

  // ─── LANCHES ────────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Baguete Bauru", preco: 18.5, categoriaId: lanches.id },
      { nome: "Baguete c/ Ovos Mexidos", preco: 15.0, categoriaId: lanches.id },
      { nome: "Baguete com Ovos Mexidos e Requeijão", preco: 15.0, categoriaId: lanches.id },
      { nome: "Baguete de Carne Desfiada", preco: 25.0, categoriaId: lanches.id },
      { nome: "Baguete de Carne Diversas", preco: 17.5, categoriaId: lanches.id },
      { nome: "Baguete de Frango", preco: 16.5, categoriaId: lanches.id },
      { nome: "Baguete de Frango com Alface e Tomate", preco: 18.5, categoriaId: lanches.id },
      { nome: "Baguete de Frios", preco: 16.0, categoriaId: lanches.id },
      { nome: "Baguete de Linguiça Queijo, Alface e Tomate", preco: 26.0, categoriaId: lanches.id },
      { nome: "Baguete de Queijo com Frango", preco: 20.5, categoriaId: lanches.id },
      { nome: "Baguete Especial Presunto Parma, Muss. de Búfala", preco: 25.0, categoriaId: lanches.id },
      { nome: "Baguete Minas", preco: 16.0, categoriaId: lanches.id },
      { nome: "Baguete Minas c/ Ovos Mexidos e Tomate Cereja", preco: 21.0, categoriaId: lanches.id },
      { nome: "Baguete Misto Quente", preco: 16.5, categoriaId: lanches.id },
      { nome: "Baguete Presunto Parma, Muss. de Búfala e Tomate Cereja", preco: 25.0, categoriaId: lanches.id },
      { nome: "Bauruzinho de Presunto e Queijo com Tomate", preco: 11.5, categoriaId: lanches.id },
      { nome: "Beirute", preco: 16.5, categoriaId: lanches.id },
      { nome: "Cinnamaron de Canela", preco: 16.5, categoriaId: lanches.id },
      { nome: "Croissant de Peito de Peru com Queijo", preco: 11.5, categoriaId: lanches.id },
      { nome: "Croissant de Peito de Peru c/ Provolone", preco: 11.5, categoriaId: lanches.id },
      { nome: "Croissant de Peru c/ Queijo Branco", preco: 11.5, categoriaId: lanches.id },
      { nome: "Croissant Presunto de Parma, Mussarela Búfala e Tomate Cereja", preco: 18.0, categoriaId: lanches.id },
      { nome: "Croissant Presunto e Queijo", preco: 11.5, categoriaId: lanches.id },
      { nome: "Croissant Tradicional com Manteiga", preco: 17.0, categoriaId: lanches.id },
      { nome: "Croissant Tradicional Grande", preco: 13.5, categoriaId: lanches.id },
      { nome: "Danish Salgado", preco: 11.5, categoriaId: lanches.id },
      { nome: "Enroladinho Integral de Peito de Peru e Queijo", preco: 13.0, categoriaId: lanches.id },
      { nome: "Enroladinho Integral Peito de Peru", preco: 8.5, categoriaId: lanches.id },
      { nome: "Enroladinho Presunto e Queijo", preco: 10.0, categoriaId: lanches.id },
      { nome: "Lanche Natural", preco: 15.5, categoriaId: lanches.id },
      { nome: "Misto Clássico - Tostex", preco: 18.9, categoriaId: lanches.id },
      { nome: "N York Roll", preco: 18.5, categoriaId: lanches.id },
      { nome: "NY Roll Supreme", preco: 18.5, categoriaId: lanches.id },
      { nome: "Ovos Mexidos com Queijo na Baguete", preco: 18.0, categoriaId: lanches.id },
      { nome: "Ovos Mexidos com Requeijão Croissant", preco: 19.9, categoriaId: lanches.id },
      { nome: "Ovos Mexidos com Requeijão na Baguete", preco: 15.0, categoriaId: lanches.id },
      { nome: "Ovo Mexido 01 Unidade", preco: 4.0, categoriaId: lanches.id },
      { nome: "Pain de Chocolate", preco: 16.5, categoriaId: lanches.id },
      { nome: "Pão com Manteiga", preco: 6.0, categoriaId: lanches.id },
      { nome: "Pão com Manteiga na Chapa", preco: 8.0, categoriaId: lanches.id },
      { nome: "Pão de Batata c/ Catupiry Premium", preco: 13.0, categoriaId: lanches.id },
      { nome: "Pão de Batata c/ Requeijão", preco: 11.5, categoriaId: lanches.id },
      { nome: "Pão de Batata Calabresa", preco: 11.5, categoriaId: lanches.id },
      { nome: "Pão de Batata de Catupiry", preco: 11.5, categoriaId: lanches.id },
      { nome: "Pão de Batata de Frango", preco: 11.5, categoriaId: lanches.id },
      { nome: "Pão de Batata Quatro Queijos", preco: 11.5, categoriaId: lanches.id },
      { nome: "Pão de Queijo - Lanche 90 GRS", preco: 9.0, categoriaId: lanches.id },
      { nome: "Pão de Queijo Gourmet c/ Catupiry 50 GRS", preco: 4.5, categoriaId: lanches.id },
      { nome: "Pão de Queijo Gourmet de 20 GR", preco: 2.5, categoriaId: lanches.id },
      { nome: "Pão de Queijo Gourmet Tradicional 50 GRS", preco: 4.5, categoriaId: lanches.id },
      { nome: "Pão de Queijo Recheado Calabresa 50 GRS", preco: 4.5, categoriaId: lanches.id },
      { nome: "Sand Wrap de Frango", preco: 15.0, categoriaId: lanches.id },
      { nome: "Sand Wrap Peito de Peru", preco: 16.0, categoriaId: lanches.id },
      { nome: "Sanduíche Baguete de Frango", preco: 15.5, categoriaId: lanches.id },
      { nome: "Sanduíche Carne Desfiada", preco: 21.5, categoriaId: lanches.id },
      { nome: "Sanduíche de Queijo com Ovo", preco: 15.0, categoriaId: lanches.id },
      { nome: "Sanduíche Integral de Atum", preco: 17.0, categoriaId: lanches.id },
      { nome: "Sanduíche Pequeno Presunto e Queijo", preco: 8.0, categoriaId: lanches.id },
      { nome: "Sanduíche Presunto de Parma / Mussarela Búfala / Rúcula", preco: 25.0, categoriaId: lanches.id },
      { nome: "Tostex Presunto e Queijo", preco: 16.0, categoriaId: lanches.id },
      { nome: "Cesta com 5 Pães de Queijo Gourmet 40 GRS Cada", preco: 18.0, categoriaId: lanches.id },
      { nome: "Cestinha Palitos de Pão de Queijo c/ 6 Unidades", preco: 16.0, categoriaId: lanches.id },
      { nome: "Cestinha Pão de Queijo c/ 5 Unidades", preco: 10.0, categoriaId: lanches.id },
      { nome: "Cestinha Pão de Queijo Gourmet c/ 10 Unidades", preco: 20.0, categoriaId: lanches.id },
      { nome: "Mini Croissant Tradicional Pote c/ 10 Unidades", preco: 15.0, categoriaId: lanches.id },
      { nome: "Mini Pão de Queijo Gourmet Pote c/ 10 Unidades", preco: 20.0, categoriaId: lanches.id },
      { nome: "Mini Pão de Queijo Gourmet Pote c/ 5 Unidades", preco: 10.0, categoriaId: lanches.id },
      { nome: "Mini Palitos Pão de Queijo - Pote c/ 6 Unidades", preco: 16.0, categoriaId: lanches.id },
    ],
  });

  // ─── SALGADOS ───────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Bolinho de Bacalhau", preco: 15.0, categoriaId: salgados.id },
      { nome: "Bolinho de Carne", preco: 11.5, categoriaId: salgados.id },
      { nome: "Coxinha de Frango", preco: 11.5, categoriaId: salgados.id },
      { nome: "Coxinha de Frango com Catupiry", preco: 11.5, categoriaId: salgados.id },
      { nome: "Kibe", preco: 11.5, categoriaId: salgados.id },
      { nome: "Mini Esfiras de Carne c/ 10 Unidades", preco: 16.0, categoriaId: salgados.id },
      { nome: "Pastel de Carne", preco: 11.5, categoriaId: salgados.id },
      { nome: "Trouxinha de Carne Seca", preco: 11.5, categoriaId: salgados.id },
      { nome: "Trouxinha de Ricota Integral", preco: 13.0, categoriaId: salgados.id },
    ],
  });

  // ─── TORTAS E QUICHES ───────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Empada de Camarão", preco: 15.5, categoriaId: tortasSalgadas.id },
      { nome: "Empada de Frango", preco: 14.5, categoriaId: tortasSalgadas.id },
      { nome: "Empada de Palmito", preco: 14.5, categoriaId: tortasSalgadas.id },
      { nome: "Esfira de Berinjela", preco: 11.5, categoriaId: tortasSalgadas.id },
      { nome: "Esfira de Bauru", preco: 8.5, categoriaId: tortasSalgadas.id },
      { nome: "Esfira de Calabresa", preco: 11.5, categoriaId: tortasSalgadas.id },
      { nome: "Esfira de Calabresa c/ Cream Cheese", preco: 10.0, categoriaId: tortasSalgadas.id },
      { nome: "Esfira de Carne", preco: 11.5, categoriaId: tortasSalgadas.id },
      { nome: "Esfira de Frango", preco: 11.5, categoriaId: tortasSalgadas.id },
      { nome: "Esfira de Frango Integral", preco: 13.0, categoriaId: tortasSalgadas.id },
      { nome: "Esfira de Margarita", preco: 8.5, categoriaId: tortasSalgadas.id },
      { nome: "Pizza Brotinho Div. Sabores", preco: 15.5, categoriaId: tortasSalgadas.id },
      { nome: "Pizza Folhada Calabresa c/ Catupiry", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Pizza Folhada de Escarola", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Pizza Folhada de Palmito", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Pizza Folhada Frango c/ Catupiry", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Pizza Folhada Portuguesa", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Pizza Folhada Quatro Queijos", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Quiche 4 Queijos", preco: 17.5, categoriaId: tortasSalgadas.id },
      { nome: "Quiche Alho Porô", preco: 17.5, categoriaId: tortasSalgadas.id },
      { nome: "Quiche Caseira", preco: 13.0, categoriaId: tortasSalgadas.id },
      { nome: "Quiche de Alho Porô + Salada Média", preco: 25.0, categoriaId: tortasSalgadas.id },
      { nome: "Quiche de Alho Porô - Caseira", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Quiche de Brócolis", preco: 17.5, categoriaId: tortasSalgadas.id },
      { nome: "Quiche de Legumes", preco: 17.5, categoriaId: tortasSalgadas.id },
      { nome: "Quiche de Palmito", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Quiche Lorraine", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Torta da Casa - Frango c/ Palmito", preco: 14.5, categoriaId: tortasSalgadas.id },
      { nome: "Torta de Frango com Requeijão - Fatia", preco: 15.5, categoriaId: tortasSalgadas.id },
      { nome: "Torta de Frango Caseira - Fatia", preco: 20.0, categoriaId: tortasSalgadas.id },
      { nome: "Torta Inteira de Palmito da Carasi", preco: 120.0, categoriaId: tortasSalgadas.id },
      { nome: "Torta Salgada de Frango com Requeijão - Fatia", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Torta Salgada de Palmito - Fatia", preco: 16.5, categoriaId: tortasSalgadas.id },
      { nome: "Tortinha de Frango c/ Requeijão", preco: 13.5, categoriaId: tortasSalgadas.id },
      { nome: "Tortinha de Frango c/ Requeijão 150 GR", preco: 14.5, categoriaId: tortasSalgadas.id },
      { nome: "Tortinha de Limão", preco: 13.5, categoriaId: tortasSalgadas.id },
      { nome: "Tortinha de Palmito Caseira", preco: 16.0, categoriaId: tortasSalgadas.id },
    ],
  });

  // ─── SALADAS ────────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Salada c/ Frango Desfiado", preco: 30.0, categoriaId: saladas.id },
      { nome: "Salada Completa", preco: 27.0, categoriaId: saladas.id },
      { nome: "Salada Completa com Fatia de Torta de Palmito", preco: 39.5, categoriaId: saladas.id },
      { nome: "Salada Completa com Fatia de Torta de Frango", preco: 39.5, categoriaId: saladas.id },
      { nome: "Salada Completa com Filé de Frango", preco: 43.5, categoriaId: saladas.id },
      { nome: "Salada de Frango", preco: 23.0, categoriaId: saladas.id },
      { nome: "Salada de Fruta Grande 180 GR", preco: 13.5, categoriaId: saladas.id },
      { nome: "Salada de Fruta Pequena 120 GR", preco: 11.0, categoriaId: saladas.id },
      { nome: "Salada de Massa Atum e Limão", preco: 24.0, categoriaId: saladas.id },
      { nome: "Salada de Tabule e Kibe", preco: 27.0, categoriaId: saladas.id },
      { nome: "Salada Ilha de Capri", preco: 24.0, categoriaId: saladas.id },
      { nome: "Salada Italiana", preco: 24.0, categoriaId: saladas.id },
      { nome: "Salada Média", preco: 13.5, categoriaId: saladas.id },
      { nome: "Salada Média c/ Kibe", preco: 27.0, categoriaId: saladas.id },
      { nome: "Salada Média c/ Quiche de Alho Porô", preco: 27.0, categoriaId: saladas.id },
      { nome: "Salada Média com Filé de Frango", preco: 27.0, categoriaId: saladas.id },
      { nome: "Salada Média com Torta de Frango", preco: 27.0, categoriaId: saladas.id },
      { nome: "Salada Média com Torta de Palmito", preco: 27.0, categoriaId: saladas.id },
      { nome: "Salada Menu Nova York", preco: 28.5, categoriaId: saladas.id },
      { nome: "Salada Mussarela Búfala", preco: 24.0, categoriaId: saladas.id },
      { nome: "Salada Pronta / Atum", preco: 23.5, categoriaId: saladas.id },
      { nome: "Salada Pronta / Caesar", preco: 24.0, categoriaId: saladas.id },
      { nome: "Salada Pronta / Frango", preco: 23.0, categoriaId: saladas.id },
      { nome: "Salada Pronta / Ovo de Codorna 180 GR", preco: 20.0, categoriaId: saladas.id },
      { nome: "Salada Pronta / Saladex", preco: 21.6, categoriaId: saladas.id },
      { nome: "Salada Pronta / Saladex 150 GR", preco: 17.5, categoriaId: saladas.id },
      { nome: "Sachê para Salada Caesar", preco: 2.5, categoriaId: saladas.id },
      { nome: "Kibe com Salada de Tabule", preco: 27.0, categoriaId: saladas.id },
      { nome: "Kibe para Salada", preco: 20.0, categoriaId: saladas.id },
    ],
  });

  // ─── SOPAS ──────────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Sopa - Abóbora c/ Carne Seca", preco: 27.0, categoriaId: sopas.id },
      { nome: "Sopa - Caldo de Feijão", preco: 27.0, categoriaId: sopas.id },
      { nome: "Sopa - Caldo de Legumes c/ Frango", preco: 27.0, categoriaId: sopas.id },
      { nome: "Sopa - Caldo Verde", preco: 27.0, categoriaId: sopas.id },
      { nome: "Sopa - Canja de Galinha", preco: 27.0, categoriaId: sopas.id },
      { nome: "Sopa - Creme de Queijos", preco: 27.0, categoriaId: sopas.id },
      { nome: "Sopa - Mandioquinha c/ Carne Seca", preco: 27.0, categoriaId: sopas.id },
      { nome: "Sopa Congelada - Caldo de Feijão", preco: 24.0, categoriaId: sopas.id },
      { nome: "Sopa Congelada - Caldo de Legumes c/ Frango", preco: 23.0, categoriaId: sopas.id },
      { nome: "Sopa Congelada - Caldo Verde", preco: 23.0, categoriaId: sopas.id },
      { nome: "Sopa Congelada - Canja de Galinha", preco: 23.0, categoriaId: sopas.id },
      { nome: "Sopa Congelada - Creme de Queijos", preco: 23.0, categoriaId: sopas.id },
      { nome: "Sopa Congelada - Abóbora c/ Carne Seca", preco: 23.0, categoriaId: sopas.id },
      { nome: "Sopa Congelada - Mandioquinha c/ Carne Seca", preco: 24.0, categoriaId: sopas.id },
    ],
  });

  // ─── DOCES E SOBREMESAS ─────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Alfajor Sr. Ogro", preco: 13.0, categoriaId: doces.id },
      { nome: "Beijo Doce com Leite Condensado e Coco", preco: 4.0, categoriaId: doces.id },
      { nome: "Bolo de Cenoura c/ Brigadeiro Zero - Fatia", preco: 16.0, categoriaId: doces.id },
      { nome: "Bolo de Cenoura com Cobertura Chocolate", preco: 12.0, categoriaId: doces.id },
      { nome: "Bolo de Chocolate sem Glúten", preco: 11.0, categoriaId: doces.id },
      { nome: "Bolo de Laranja Caseiro - Fatia", preco: 6.0, categoriaId: doces.id },
      { nome: "Bolo de Limão Caseiro - Fatia", preco: 6.0, categoriaId: doces.id },
      { nome: "Bolo de Pote", preco: 20.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Chocolate Especial", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Cocada", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Lacta", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Mousse de Limão", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Mousse de Maracujá MB", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Mousse de Maracujá MP", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Ninho", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Ninho com Nutella", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Ovomaltine", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Prestígio", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Zero Açúcar Abacaxi", preco: 21.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Zero Açúcar Chocolate", preco: 25.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Zero Açúcar Limão", preco: 25.0, categoriaId: doces.id },
      { nome: "Bolo de Pote - Zero Açúcar Pistache", preco: 25.0, categoriaId: doces.id },
      { nome: "Bolo de Pote Abacaxi", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote Cenoura com Chocolate", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote Diamante Negro", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote Doce de Leite", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote Doce de Leite Ameixa", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote Doce de Leite Nozes", preco: 18.0, categoriaId: doces.id },
      { nome: "Bolo de Pote Pistache", preco: 20.0, categoriaId: doces.id },
      { nome: "Bolo de Pote Zero Açúcar Doce de Leite", preco: 25.0, categoriaId: doces.id },
      { nome: "Bolo Fatia", preco: 10.0, categoriaId: doces.id },
      { nome: "Bolo Gelado", preco: 15.0, categoriaId: doces.id },
      { nome: "Bolo Gelado - Cocada", preco: 12.0, categoriaId: doces.id },
      { nome: "Bolo Mousse Chocolate - Fatia", preco: 12.0, categoriaId: doces.id },
      { nome: "Bolo Mousse de Limão - Fatia", preco: 15.5, categoriaId: doces.id },
      { nome: "Bolo Prestígio Zero - Fatia", preco: 14.0, categoriaId: doces.id },
      { nome: "Bolo Red Velvet - Fatia", preco: 16.0, categoriaId: doces.id },
      { nome: "Bombocado", preco: 5.0, categoriaId: doces.id },
      { nome: "Brigadeirão", preco: 16.0, categoriaId: doces.id },
      { nome: "Brigadeiro Caixinha com 4 Unidades", preco: 16.0, categoriaId: doces.id },
      { nome: "Brigadeiro e Beijinho", preco: 7.0, categoriaId: doces.id },
      { nome: "Brownie de Avelã", preco: 13.0, categoriaId: doces.id },
      { nome: "Brownie Doce de Leite", preco: 13.0, categoriaId: doces.id },
      { nome: "Brownie Tradicional", preco: 12.0, categoriaId: doces.id },
      { nome: "Brownie Zero", preco: 13.0, categoriaId: doces.id },
      { nome: "Canolê de Doce de Leite", preco: 12.0, categoriaId: doces.id },
      { nome: "Canolê de Ninho", preco: 12.0, categoriaId: doces.id },
      { nome: "Cheesecake Frutas Vermelhas - Fatia", preco: 18.9, categoriaId: doces.id },
      { nome: "Choux", preco: 16.0, categoriaId: doces.id },
      { nome: "Cookie - Mini Tradicional", preco: 9.0, categoriaId: doces.id },
      { nome: "Cookie Dark Brigadeiro", preco: 21.0, categoriaId: doces.id },
      { nome: "Cookie Dark Laka", preco: 21.0, categoriaId: doces.id },
      { nome: "Cookie Lemon Blackberry", preco: 21.0, categoriaId: doces.id },
      { nome: "Cookie Nutella", preco: 21.0, categoriaId: doces.id },
      { nome: "Cookie Pistachio", preco: 21.0, categoriaId: doces.id },
      { nome: "Cookie Red Velvet", preco: 21.0, categoriaId: doces.id },
      { nome: "Cookie Tradicional", preco: 18.0, categoriaId: doces.id },
      { nome: "Cuca de Uva", preco: 10.0, categoriaId: doces.id },
      { nome: "Donuts Div. Sabores", preco: 9.0, categoriaId: doces.id },
      { nome: "Macarom", preco: 6.5, categoriaId: doces.id },
      { nome: "Marmitinha Brownie Tradicional", preco: 15.0, categoriaId: doces.id },
      { nome: "Mini Banoffee", preco: 8.0, categoriaId: doces.id },
      { nome: "Mini Cookies Cakes Cenoura com Nutella", preco: 4.0, categoriaId: doces.id },
      { nome: "Mousse Pequeno Caseiro", preco: 12.0, categoriaId: doces.id },
      { nome: "Paçoca Pacoquita Santa Helena", preco: 2.5, categoriaId: doces.id },
      { nome: "Palha Italiana", preco: 4.0, categoriaId: doces.id },
      { nome: "Palha Italiana Pote", preco: 16.0, categoriaId: doces.id },
      { nome: "Pão de Mel", preco: 9.5, categoriaId: doces.id },
      { nome: "Pão de Mel ao Licor Pequeno", preco: 5.0, categoriaId: doces.id },
      { nome: "Pão de Mel Recheado Grande", preco: 8.0, categoriaId: doces.id },
      { nome: "Pão de Mel Sr. Ogro", preco: 10.0, categoriaId: doces.id },
      { nome: "Pé de Moça - Doce", preco: 3.5, categoriaId: doces.id },
      { nome: "Pudim Caseiro", preco: 16.5, categoriaId: doces.id },
      { nome: "Pudim de Leite", preco: 12.0, categoriaId: doces.id },
      { nome: "Torta Banoffee - Fatia", preco: 18.9, categoriaId: doces.id },
      { nome: "Torta de Banoffee Caseira", preco: 15.0, categoriaId: doces.id },
      { nome: "Torta de Chocolate Zero Açúcar - Fatia", preco: 18.9, categoriaId: doces.id },
      { nome: "Torta de Uva - Fatia", preco: 18.9, categoriaId: doces.id },
      { nome: "Torta Doce de Morango (Tartelette)", preco: 18.0, categoriaId: doces.id },
      { nome: "Torta Doce Cheesecake Frutas Vermelhas", preco: 15.5, categoriaId: doces.id },
      { nome: "Torta Doce de Limão - Fatia", preco: 22.0, categoriaId: doces.id },
      { nome: "Torta Doce Holandesa - Fatia", preco: 15.9, categoriaId: doces.id },
      { nome: "Torta Doce Nut Ninho", preco: 16.5, categoriaId: doces.id },
      { nome: "Torta Doce Tiramissu - Fatia", preco: 16.5, categoriaId: doces.id },
      { nome: "Torta Doce Triplo Chocolate - Fatia", preco: 15.9, categoriaId: doces.id },
      { nome: "Torta La Creme - Fatia", preco: 18.9, categoriaId: doces.id },
      { nome: "Torta Lemon - Fatia", preco: 15.9, categoriaId: doces.id },
      { nome: "Torta Pistachio - Fatia", preco: 15.9, categoriaId: doces.id },
      { nome: "Torta Tiramissu - Fatia", preco: 19.8, categoriaId: doces.id },
      { nome: "Torta Triplo Chocolate - Fatia", preco: 15.9, categoriaId: doces.id },
      { nome: "Wafer de Nutella - Amor Gourmet", preco: 12.0, categoriaId: doces.id },
      { nome: "Waffle com Cobertura Chocolate", preco: 5.0, categoriaId: doces.id },
      { nome: "Waffle com Cobertura Chocolate Branco", preco: 5.0, categoriaId: doces.id },
    ],
  });

  // ─── CHOCOLATES E GULOSEIMAS ────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Balas Azedinha Morango", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Balas Fruittella Mastigável Morango", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Balas Halls Cereja", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Balas Halls de Melancia", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Balas Halls Extra Forte", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Balas Halls Menta", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Balas Halls Morango", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Balas Mentos Fruit", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Balas Mentos Kiss SF Lata", preco: 16.0, categoriaId: guloseimas.id },
      { nome: "Balas Mentos Menta", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Balas Skittles Original 38 GR", preco: 5.5, categoriaId: guloseimas.id },
      { nome: "Barrinha Bananinha", preco: 5.5, categoriaId: guloseimas.id },
      { nome: "Barrinha Bananinha Sem Açúcar e Glúten", preco: 6.5, categoriaId: guloseimas.id },
      { nome: "Barrinha Chocolate Bauduco", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Barrinha Goiaba Bauduco", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Barrinha Nutella Bready", preco: 8.0, categoriaId: guloseimas.id },
      { nome: "Baton ao Leite", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Baton Branco", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Baton Extra Milk", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Baton Recheio Morango", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Biscoito Beijinho 150 GR", preco: 9.5, categoriaId: guloseimas.id },
      { nome: "Biscoito de Chocolate 150 GR", preco: 9.5, categoriaId: guloseimas.id },
      { nome: "Biscoito de Polvilho 70 GR", preco: 6.0, categoriaId: guloseimas.id },
      { nome: "Biscoito de Polvilho Salgado Cassini 100 GR", preco: 7.5, categoriaId: guloseimas.id },
      { nome: "Biscoito Goiabinha 150 GR", preco: 9.5, categoriaId: guloseimas.id },
      { nome: "Biscoito Nata 150 GR", preco: 9.5, categoriaId: guloseimas.id },
      { nome: "Biscoitos Sequilhos Div. Sabores 120 GR", preco: 5.0, categoriaId: guloseimas.id },
      { nome: "Biscoitos Amanteigados 90 GR", preco: 5.0, categoriaId: guloseimas.id },
      { nome: "Chiclete Mentos Cool White", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chiclete Mentos Pure", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Chiclete Trident Cereja Ice", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chiclete Trident Herbal", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chiclete Trident Hortelã", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chiclete Trident Intense", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chiclete Trident Melancia", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chiclete Trident Menta", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chiclete Trident Morango", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chips Batata Especial", preco: 12.5, categoriaId: guloseimas.id },
      { nome: "Chips Batata Lisa Original", preco: 8.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Bis Branco 45 GR", preco: 8.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Bis Oreo 45 GR", preco: 6.5, categoriaId: guloseimas.id },
      { nome: "Chocolate Bis Wafer ao Leite 45 GR", preco: 8.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Chocotubes 25 GR", preco: 5.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Ferrero Rocher", preco: 10.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Hershey Chocotubes N Creme 25 GR", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Kinder Bueno", preco: 13.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Kinder Bueno Branco", preco: 10.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Kinder ao Leite", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chocolate KitKat ao Leite", preco: 6.5, categoriaId: guloseimas.id },
      { nome: "Chocolate KitKat Branco", preco: 6.5, categoriaId: guloseimas.id },
      { nome: "Chocolate Minichoco Branco Linea 13 G", preco: 5.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Minichoco Leite Linea 13 G", preco: 5.0, categoriaId: guloseimas.id },
      { nome: "Chocolate MMs Amendoim 45 GR", preco: 6.5, categoriaId: guloseimas.id },
      { nome: "Chocolate MMs ao Leite 45 GR", preco: 6.5, categoriaId: guloseimas.id },
      { nome: "Chocolate Mumu Kids", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Chocolate Snickers Branco", preco: 6.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Snickers Morango 42 G", preco: 7.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Snickers Tradicional", preco: 7.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Sonho de Valsa - Bombom", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Chocolate Sonho de Valsa Stick Wafer", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Stick 25 GR", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Stikadinho 25 GR", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Suflair Pequeno", preco: 10.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Talento", preco: 7.5, categoriaId: guloseimas.id },
      { nome: "Chocolate Trento", preco: 6.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Trento Avelã", preco: 4.5, categoriaId: guloseimas.id },
      { nome: "Chocolate Trento Massimos", preco: 6.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Trento Mousse de Maracujá", preco: 6.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Zero Linea", preco: 5.0, categoriaId: guloseimas.id },
      { nome: "Chocolate Twix", preco: 3.0, categoriaId: guloseimas.id },
      { nome: "Drops Azedinha Morango", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Drops Halls Cereja", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Drops Halls Extra Forte", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Drops Halls Menta", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Drops Halls Morango", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Drops Lilith Morango", preco: 3.5, categoriaId: guloseimas.id },
      { nome: "Drops Mentos Frutas", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Drops Mentos Menta", preco: 4.0, categoriaId: guloseimas.id },
      { nome: "Drops Skittles Original 38 GR", preco: 5.5, categoriaId: guloseimas.id },
      { nome: "Fini Minhoquinhas Gelatinosas", preco: 5.0, categoriaId: guloseimas.id },
      { nome: "Fini Tubes Morango Cítrico 80 GR", preco: 9.5, categoriaId: guloseimas.id },
      { nome: "Fini Mini Minhoca", preco: 3.9, categoriaId: guloseimas.id },
      { nome: "Pipoca Doce Galak", preco: 15.0, categoriaId: guloseimas.id },
      { nome: "Pipoca Doce Kit Kat", preco: 15.0, categoriaId: guloseimas.id },
      { nome: "Pipoca Doce Sabor Leite Ninho", preco: 15.0, categoriaId: guloseimas.id },
      { nome: "Pipoca Salgada Azeite e Ervas", preco: 6.5, categoriaId: guloseimas.id },
      { nome: "Pipoca Salgada Cebola & Salsa", preco: 6.5, categoriaId: guloseimas.id },
      { nome: "Tic Tac Laranja", preco: 4.5, categoriaId: guloseimas.id },
    ],
  });

  // ─── BEBIDAS ────────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Água Crystal com Gás 500 ml", preco: 6.0, categoriaId: bebidas.id },
      { nome: "Água Crystal sem Gás 500 ml", preco: 6.0, categoriaId: bebidas.id },
      { nome: "Água de Coco Dikoko 200 ml", preco: 6.5, categoriaId: bebidas.id },
      { nome: "Água Tônica Antártica Lata", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Água Tônica Petra", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Coca Cola em Lata 350 ml", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Coca Cola Zero Lata 350 ml", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Coca Cola Pequena", preco: 5.0, categoriaId: bebidas.id },
      { nome: "Energético Monster Mango Loco", preco: 19.0, categoriaId: bebidas.id },
      { nome: "Energético Monster Tradicional", preco: 17.0, categoriaId: bebidas.id },
      { nome: "Energético Red Bull Melancia", preco: 17.0, categoriaId: bebidas.id },
      { nome: "Energético Red Bull Sugar", preco: 17.0, categoriaId: bebidas.id },
      { nome: "Energético Red Bull Tradicional", preco: 17.0, categoriaId: bebidas.id },
      { nome: "Energético Red Bull Tropical", preco: 17.0, categoriaId: bebidas.id },
      { nome: "Fanta Laranja", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Gatorade 500 ml", preco: 12.0, categoriaId: bebidas.id },
      { nome: "Guaraná Antártica em Lata 350 ml", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Guaraná Antártica Zero", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Refrigerante Kombucha Devi - Abacaxi com Gengibre", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Refrigerante Kombucha Devi - Maçã Gengibre", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Refrigerante Natural Devi - Frutas Vermelhas", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Refrigerante Natural Devi - Limão Siciliano", preco: 8.0, categoriaId: bebidas.id },
      { nome: "Suco Abacaxi c/ Hortelã - Ateliê", preco: 11.0, categoriaId: bebidas.id },
      { nome: "Suco Acerola Laranja 280 ml", preco: 10.0, categoriaId: bebidas.id },
      { nome: "Suco de Laranja 280 ml", preco: 10.0, categoriaId: bebidas.id },
      { nome: "Suco de Laranja Ateliê 280 ml", preco: 11.0, categoriaId: bebidas.id },
      { nome: "Suco de Manga c/ Maracujá Ateliê", preco: 11.0, categoriaId: bebidas.id },
      { nome: "Suco de Maracujá Natural 500 ml", preco: 15.0, categoriaId: bebidas.id },
      { nome: "Suco de Uva 280 ml", preco: 12.0, categoriaId: bebidas.id },
      { nome: "Suco Del Valle - Manga 290 ml", preco: 10.0, categoriaId: bebidas.id },
      { nome: "Suco Del Valle - Pêssego 290 ml", preco: 10.0, categoriaId: bebidas.id },
      { nome: "Suco Del Valle - Uva 290 ml", preco: 10.0, categoriaId: bebidas.id },
      { nome: "Suco Del Valle - Maracujá", preco: 10.0, categoriaId: bebidas.id },
      { nome: "Suco Detox Verde", preco: 15.0, categoriaId: bebidas.id },
      { nome: "Suco Natural One - Laranja", preco: 12.0, categoriaId: bebidas.id },
      { nome: "Suco Natural One - Maracujá", preco: 12.0, categoriaId: bebidas.id },
      { nome: "Suco Natural One - Uva", preco: 12.0, categoriaId: bebidas.id },
      { nome: "Sucos Natural 300 ml", preco: 12.0, categoriaId: bebidas.id },
    ],
  });

  // ─── EMBALAGENS ─────────────────────────────────────────────────────────────
  await prisma.produto.createMany({
    data: [
      { nome: "Embalagem Copo Descartável", preco: 1.0, categoriaId: embalagens.id },
      { nome: "Embalagem para Almoço", preco: 2.0, categoriaId: embalagens.id },
      { nome: "Embalagem para Baguete", preco: 1.0, categoriaId: embalagens.id },
      { nome: "Embalagem para Hamburguer", preco: 1.0, categoriaId: embalagens.id },
      { nome: "Embalagem para Tortas", preco: 1.0, categoriaId: embalagens.id },
    ],
  });

  const total = await prisma.produto.count();
  console.log(`\n✓ ${total} produtos criados em 13 categorias!`);
  console.log("Dados iniciais criados com sucesso!");
  console.log("Use PIN 2262 (Admin) ou 1234 (Maria) para entrar no sistema.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
